# 1. Imagen base de Node.js
FROM node:18-alpine

# 2. Carpeta de trabajo dentro del contenedor
WORKDIR /app

# 3. Instalar dependencias
COPY package*.json ./
RUN npm install

# 4. Copiar el código fuente
COPY . .

# 5. Puerto de React
EXPOSE 3000

# 6. Comando para arrancar en modo desarrollo
CMD ["npm", "start"]