import type { CSSProperties } from 'react';

export const s: { [key: string]: any } = {
    container: {
        padding: '120px 40px 60px',
        maxWidth: '1600px',
        margin: '0 auto',
        minHeight: '100vh',
        boxSizing: 'border-box',
    },
    header: {
        textAlign: 'center',
        marginBottom: '60px',
    },
    tituloSeccion: {
        fontSize: '3.5rem',
        color: '#d81b60',
        fontWeight: '900',
        margin: 0,
        letterSpacing: '-1px',
    },
    subtitulo: {
        fontSize: '1.2rem',
        color: '#666',
        marginTop: '10px',
    },
    btnCrear: {
        marginTop: '25px',
        padding: '15px 35px',
        backgroundColor: '#000',
        color: '#fff',
        border: 'none',
        borderRadius: '50px',
        fontWeight: 'bold',
        cursor: 'pointer',
        fontSize: '1rem',
    },
    // GRID DE 4 COLUMNAS REALES
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)', // Fuerza 4 columnas iguales
        gap: '30px',
        width: '100%',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: '35px',
        padding: '35px',
        boxShadow: '0 15px 40px rgba(0,0,0,0.05)',
        border: '1px solid #fce4ec',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        textAlign: 'center',
        transition: 'transform 0.3s ease',
    },
    nombreTxt: {
        fontSize: '1.8rem',
        fontWeight: '800',
        color: '#ad1457',
        margin: '0 0 10px 0',
    },
    precioTag: {
        display: 'inline-block',
        backgroundColor: '#fce4ec',
        color: '#d81b60',
        padding: '6px 20px',
        borderRadius: '20px',
        fontWeight: 'bold',
        fontSize: '1.2rem',
        marginBottom: '20px',
    },
    btnInfo: {
        width: '100%',
        padding: '14px',
        backgroundColor: '#fff',
        color: '#d81b60',
        border: '2px solid #d81b60',
        borderRadius: '50px',
        fontWeight: 'bold',
        cursor: 'pointer',
        fontSize: '1rem',
    },

    // --- FORMULARIOS (NUEVO/EDITAR) ---
    modalOverlay: {
        position: 'fixed',
        top: 0, left: 0, width: '100%', height: '100%',
        backgroundColor: 'rgba(0,0,0,0.6)',
        display: 'flex', justifyContent: 'center', alignItems: 'center',
        zIndex: 2000,
        backdropFilter: 'blur(8px)',
    },
    modalContent: {
        backgroundColor: 'white',
        padding: '45px',
        borderRadius: '45px',
        maxWidth: '650px', 
        width: '90%',
        textAlign: 'center',
        boxShadow: '0 25px 70px rgba(0,0,0,0.25)',
    },
    modalTitulo: {
        color: '#ad1457',
        fontSize: '2.2rem',
        marginBottom: '30px',
        fontWeight: '900',
    },
    formGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr', 
        gap: '20px',
        marginBottom: '20px',
    },
    input: {
        width: '100%',
        padding: '18px 25px',
        borderRadius: '20px',
        border: '2px solid #fce4ec',
        fontSize: '1.1rem',
        boxSizing: 'border-box',
        outline: 'none',
        transition: 'all 0.3s ease',
        fontFamily: 'inherit',
        backgroundColor: '#fdfdfd',
    },
    textarea: {
        width: '100%',
        height: '140px',
        padding: '18px 25px',
        borderRadius: '20px',
        border: '2px solid #fce4ec',
        fontSize: '1.1rem',
        boxSizing: 'border-box',
        fontFamily: 'inherit',
        resize: 'none',
        marginBottom: '30px',
        backgroundColor: '#fdfdfd',
    },
    btnGuardar: {
        padding: '18px 45px',
        backgroundColor: '#d81b60', 
        color: 'white',
        border: 'none',
        borderRadius: '50px',
        fontWeight: 'bold',
        fontSize: '1.2rem',
        cursor: 'pointer',
        flex: 1,
        transition: '0.3s',
    },
    btnCancelar: {
        padding: '18px 45px',
        backgroundColor: '#fff',
        color: '#888',
        border: '2px solid #eee',
        borderRadius: '50px',
        fontWeight: 'bold',
        fontSize: '1.2rem',
        cursor: 'pointer',
        flex: 1,
        transition: '0.3s',
    }
};