DROP DATABASE IF EXISTS PASTELERIA;
CREATE DATABASE PASTELERIA;
USE PASTELERIA;

CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL,
    CONTRASEÑA VARCHAR(45) NOT NULL,
    ADMININISTRADOR INT 
);

CREATE TABLE REGISTRO(
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FECHA DATE NOT NULL,
    FECHA_ENTRADA timestamp NOT NULL,
    FECHA_SALIDA timestamp NULL,
    TOTAL_HORAS INT,
    ID_EMPLEADO INT,
    CONSTRAINT FK_EMPLEADO_REGISTRO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE PRODUCTOS(
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    STOCK INT NOT NULL,
    RECETA VARCHAR(10000) NOT NULL,
    PRECIO INT NOT NULL,
    ID_EMPLEADO INT NULL,
    CONSTRAINT FK_EMPLEADO_PRODUCTO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE INGREDIENTE(
    ID_INGREDIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Ingrediente',
    NOMBRE VARCHAR(20) NOT NULL COMMENT 'Nombre del Ingrediente',
    STOCK INT NOT NULL COMMENT 'Stock del Ingrediente',
    PROVEEDOR VARCHAR(20) NOT NULL COMMENT 'Proveedor del Cliente',
    CONSTRAINT PK_ID_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE)
);

CREATE TABLE Productos_Ingredientes(
    ID_Producto_Ingrediente INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,
    CONSTRAINT FK_INGREDIENTE_PRODUCTO FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID_INGREDIENTE),
    CONSTRAINT FK_PRODUCTO_INGREDIENTE FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

Create Table CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificar del Cliente',
    USUARIO VARCHAR(20) NOT NULL COMMENT 'Nombre del usuario del Cliente',
    CONTRASEÑA VARCHAR(20) NOT NULL COMMENT 'Contraseña del usuario del Cliente',
    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);


CREATE TABLE PEDIDO (
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Pedido',
    ENTREGA DATE NULL COMMENT 'Fecha del Pedido',
    TELEFONO INT NOT NULL COMMENT 'Telefono del cliente para el pedido',
    ESTADO VARCHAR(20) NULL COMMENT 'Estado del Pedido',
    ID_CLIENTE INT NULL COMMENT 'Identificador del Cliente',
    TOTALPRECIO INT NULL COMMENT 'Precio Total del Pedido',
    CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PEDIDO_PRODUCTO(
    ID_PEDIDO_PRODUCTO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de pedido y producto',
    ID_PEDIDO INT NULL COMMENT 'Identificador del Pedido',
    ID_PRODUCTO INT NULL COMMENT 'Identificador del Producto',
    CANTIDAD INT NULL COMMENT 'Cantidad del Pedido',
    CONSTRAINT PK_ID_PEDIDO_PRODUCTO PRIMARY KEY (ID_PEDIDO_PRODUCTO),
    CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

INSERT INTO empleado ( usuario, contraseña, admininistrador) VALUES ('Admin', 'Pruebas', 1);

-- Conusltas
-- select * from productos;
-- select * from pedido;
-- select * from cliente;
-- select * from pedido_producto;
-- select * from pedido;
