Admin("ID_Admin", Usuario, Contraseña)

Create Table ADMIN (
    ID_ADMIN INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL,
    CONTRASEÑA VARCHAR(45)
);

Empleado("ID_EMPLEADO", Usuario, Contraseña, "ID_Admin")

CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL,
    CONTRASEÑA VARCHAR(45),
    ID_ADMIN INT,
    CONSTRAINT FK_ADMIN_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES ADMIN(ID_EMPLEADO)
);

Registro("ID_Registro", FECHA, FECHA_ENTRADA, FECHA_SALIDA, Total_Horas ID_EMPLEADO)

CREATE TABLE REGISTRO(
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FECHA DATE NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    TOTAL_HORAS INT,
    ID_EMPLEADO INT,
    CONSTRAINT FK_EMPLEADO_REGISTRO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

Productos("ID_Productos", Nombre, Stock, Receta, Precio)

CREATE TABLE PRODUCTOS(
    ID_PRODUCTOS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    STOCK INT NOT NULL,
    RECETA VARCHAR(10000) NOT NULL,
    PRECIO INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    CONSTRAINT FK_EMPLEADO_PRODUCTO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);







